- .vscode/settings.template.json
- rslint-schema.json
- rslint.json
add json-schema for better auto completion in rslint.json
we should auto generated json schema in the future
> chore: add json-schema

- .gitignore
- cmd/rslint/lsp.go
add diags log for debugging in windows
> fix: add diags log

- .vscode/launch.template.json
- .vscode/tasks.json
when we change compiler from tsc to esbuild the problemMatcher is broken
> chore: fix vsce debugging

- packages/vscode-extension/src/Rslint.ts
> feat(extension): support LSP trace

- packages/vscode-extension/package.json
- packages/vscode-extension/src/Rslint.ts
- packages/vscode-extension/src/utils.ts
1. `local`: `local` -> `builtin`
2. `builtin`: `builtin`
3. `custom`: `custom`
> feat: support customize bin path resolving

- .gitignore
- cmd/rslint/lsp.go
add more logging for debugging windows
> chore: add more logging

- internal/linter/linter.go
- internal/rule/disable_manager.go
- internal/utils/ts_api_utils.go
Extract comments from typescript ast like what typescript-eslint does.
https://github.com/typescript-eslint/typescript-eslint/blob/7319bad3a5022be2adfbcb331451cfd85d1d786a/packages/typescript-estree/src/convert-comments.ts#L16
> feat: extract comments from ast

- .vscode/launch.template.json
- cmd/rslint/lsp.go
add pid info for attach debug to filter out specific lsp server
> chore: add pid info for debugging

- cmd/rslint/api.go
- cmd/rslint/cmd.go
- cmd/rslint/lsp.go
- cmd/rslint/lsp_test.go
- internal/linter/linter.go
- internal/utils/utils.go
align lsp implementation with tsgo for better consistency behavior
> refactor: use project service for lsp

- .github/workflows/ci.yml
> chore: add mac ci

- .github/workflows/release.yml
> chore: push tags when release

- .github/workflows/release.yml
push tags needs write permission
> chore: add write permission for publish-npm

- internal/lsp/server.go
remove unnecessary server log file
> chore: don't generate tsgo.log

- packages/vscode-extension/src/statusBar.ts
show binPath in statusBar tooltip for better understanding
> chore: show binPath in statusBar

- internal/linter/linter.go
This is also good for the performance I think.
> fix: skip everything if there's no rule

- packages/rslint/tests/__snapshots__/api.test.mjs.snap
> chore: update snapshot

- packages/rslint/.npmignore
- packages/rslint/package.json
- packages/rslint/src/browser.ts
- packages/rslint/src/index.ts
- packages/rslint/src/node.ts
- packages/rslint/src/service.ts
- packages/rslint/src/types.ts
- packages/rslint/src/worker.ts
- rslint.json
make service compatible with web worker and prepare for browser support
> refactor: make rslint compatible with browser

- website/theme/components/RuleStates/rule.tsx
> doc: fix broken rule links

- .github/actions/setup-go/action.yml
- CONTRIBUTING.md
- package.json
- scripts/apply-tsgo-patch.sh
Currently, building the project by following the instructions in CONTRIBUTING.md results in the following error.
I have added a step to apply a patch to typescript-go in CONTRIBUTING.md as part of the build process.
```
packages/rslint-api build$ rslib build
│   Rslib v0.12.4
│ info    build started...
│ ready   built in 0.13 s
│ start   generating declaration files... (esm)
│ info    declaration files prepared in 0.57 s (esm)
│ error   [api-extractor] Internal Error: Unable to determine semantic information for declaration:
│ /Users/***/workspace/rslint/typescript-go/_packages/api/src/client.ts:32:24
│ You have encountered a software defect. Please consider reporting the issue to the maintainers of this application. (esm)
│ File (esm)       Size      
│ dist/index.mjs   78.8 kB
│ error …
```
> chore: fix script name and update CONTRIBUTING.md

- .github/PULL_REQUEST_TEMPLATE.md
Add GitHub pull request template.
The same as https://github.com/web-infra-dev/rspack/blob/main/.github/PULL_REQUEST_TEMPLATE.md
> chore(workflow): add pull request template

- .github/workflows/ci.yml
the old runner go back to normal now
> chore: revert back to old runner

- package.json
- packages/rslint-api/package.json
- packages/rslint-wasm/package.json
- packages/rslint/package.json
- packages/rule-tester/package.json
- packages/vscode-extension/package.json
- pnpm-lock.yaml
use tsgo instead of tsc to catch tsgo bugs
> chore: use tsgo instead of tsc

- AGENTS.md
add fix ci instructions for ai
> docs: update AGENTS.md with CI fix instructions

- website/theme/components/Playground/ResultPanel.tsx
show ast is generated from tsgo
> chore: add tsgo notice
